services:
  - type: web
    name: tienda-pro
    env: node
    buildCommand: npm run build
    startCommand: npm start
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html